{
 "title": "Pool & Volume dashboard",
 "tags": [ "OpenEBS" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "spc",
    "label": "Storage Pool Claim",
    "query": {
     "query": "label_values(openebs_pool_status,storage_pool_claim)"
    }
   },
   {
    "name": "Pool",
    "label": "cStor Pool",
    "query": {
     "query": "label_values(openebs_pool_status{storage_pool_claim=~\"$spc\"}, cstor_pool)"
    }
   },
   {
    "name": "Replica",
    "label": "Replica",
    "query": {
     "query": "label_values(openebs_replica_status{cstor_pool=~\"$Pool\"}, vol)"
    }
   },
   {
    "name": "openebs_Volume",
    "label": "Volume",
    "query": {
     "query": "label_values(openebs_size_of_volume, openebs_pv)"
    }
   },
   {
    "name": "openebs_pvc",
    "label": "Openebs_pvc",
    "query": {
     "query": "label_values(openebs_size_of_volume{openebs_pv=~\"$openebs_Volume\"},openebs_pvc)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Size of Pool",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openebs_pool_size{cstor_pool=~\"$Pool\"}/(1024*1024*1024)",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "Used Pool Capacity",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(openebs_used_pool_capacity{cstor_pool=~\"$Pool\"})/(1024*1024*1024)",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "Free Pool Capacity",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(openebs_free_pool_capacity{cstor_pool=~\"$Pool\"})/(1024*1024*1024)",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "Pool Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openebs_pool_status{cstor_pool=~\"$Pool\"}",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "Replica Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openebs_replica_status{cstor_pool=~\"$Pool\", vol=~\"$Replica\"}",
     "legendFormat": "{{vol}}"
    }
   ]
  },
  {
   "title": "Replica Count for volume($openebs_Volume)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "openebs_total_replica_count{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}",
     "legendFormat": "total"
    },
    {
     "expr": "openebs_healthy_replica_count{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}",
     "legendFormat": "healthy"
    },
    {
     "expr": "openebs_degraded_replica_count{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}",
     "legendFormat": "degraded"
    }
   ]
  },
  {
   "title": "Volume Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openebs_volume_status{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}",
     "legendFormat": "{{openebs_pv}}"
    }
   ]
  },
  {
   "title": "Volume Total Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "openebs_size_of_volume{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}",
     "legendFormat": "{{openebs_pv}}"
    }
   ]
  },
  {
   "title": "Volume Consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "openebs_actual_used{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}",
     "legendFormat": "{{openebs_pv}}"
    }
   ]
  }
 ]
}